---
driver:
  name: vagrant
  customize:
    memory: 8096
  network:
    - ["public_network", bridge: 'eth0']

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[vfense::setup]
    attributes:
